spring.application.name=AV1-DWIII

spring.datasource.url=jdbc:mysql://localhost:3306/AV2?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=fatec

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql: true 


